### ISSUE TITLE
Render fullscreen image thumbnails as <img> tags

### ISSUE THREAD

**Issue by redallen** [patternfly/patternfly-org#1660]
To make maintenance easier, currently we render fullscreen previews using CSS transforms and some janky Javascript.

```css
.ws-preview-fullscreen {
  position: relative;
  pointer-events: none;
  width: 1280px;
  height: 800px;
  transform-origin: top left;
  /* transform: scale added in JS based on parent element width */
}

.ws-preview-container {
  position: relative;
  display: block;
}

.ws-preview__thumbnail-link {
  position: relative;
  display: inline-block;
  line-height: 0;
  overflow: hidden;
}

.ws-preview__thumbnail-link::before,
.ws-preview__thumbnail-link::after {
  position: absolute;
  z-index: 500;
  transition: .2s;
  opacity: 0;
}

.ws-preview__thumbnail-link:hover::before,
.ws-preview__thumbnail-link:hover::after {
  opacity: 1;
}

.ws-preview__thumbnail-link::before {
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  content: '';
  background-color: rgba(0,0,0,.5);
}

.ws-preview__thumbnail-link::after {
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  font-family: "Font Awesome 5 Free";
  content: "\f35d";
  font-size: 52px;
  color: rgba(255,255,255,.4);
}
```

```js
  if (isFullscreen) {
    useLayoutEffect(() => {
      const handleResize = () => {
        const resizeWidth = Math.min(
          document.getElementsByClassName('ws-example')[0].clientWidth,
          800
        );

        const scale = resizeWidth / 1280;

        setPreviewStyle({ transform: `scale(${scale})` });
        setPreviewContainerStyle({ height:`${scale * 800}px`, width:`${scale * 1280}px` });
      }

      if (!previewStyle.transform) {
        handleResize();
      }
      window.addEventListener('resize', handleResize);

      return () => window.removeEventListener('resize', handleResize);
    });
  }
```

~~We need a script that goes through a local `public` folder of a site using gatsby-theme-patternfly-org, takes screenshots, saves them back to the public folder with a cache-busting SHA like `public/img/${SHA}-fs-${componentName}-${exampleName}.png` and runs a regex to replace a placeholder `/img/${componentName}-${exampleName}.png` in `public/documentation/**.html`. We also need to make sure our JS doesn't rerender over it, this is the tricky part.~~

On the build side taking screenshots can be a post-build step. Do a build, serve it, then in another script `require('routes.js');` and visit all fullscreen pages taking 800x600px screenshots using [`puppeteer-cluster`](https://www.npmjs.com/package/puppeteer-cluster). Save them as `[route]/[example-title]-[jpg-data-hash].jpg` to the output folder webpack is configured with, which is `public`. Have script replace occurrences of `[route]/[example-title].jpg` with `[route]/[example-title]-[jpg-data-hash].jpg`. Also save them to a local folder which is copied with `copy-webpack-plugin` to `public` for use in dev mode. If the size is manageable enough, do not add them to `.gitignore` and have the `release` job in CI also commit and update the images.

On the client side loading the screenshots can be as simple as `<img src="[route]/[example-title].jpg" />` which will be replaced in the post-build step with the cache-busting SHA. An appropriate fallback can be shown for dev mode.
