### ISSUE TITLE
Documentation width limit causes a lot of wrapping

### ISSUE THREAD

**Issue by srambach** [patternfly/patternfly-org#2645]
Having the page width limited causes a lot of wrapping in documentation sections. It would be great to let those stretch further on a wider viewport.

**Comment by redallen** [comment]
I argued against max-width at first but was won over by @mcarrano in #2044. We met and chose 832px.

This is the rule in `mdx.css`, feel free to put up a PR to change it:
```css
/* Design asked for this. A nice side effect is that the TOC doesn't "jump" between pages */
.ws-mdx-content-content {
  max-width: 832px;
}
```
