### ISSUE TITLE
Bug - issue with backdrop component styles on org

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-org#4335]
If you go to any example that uses the backdrop component, you'll see that it's positioned incorrectly:
* https://staging.patternfly.org/components/about-modal/
* https://staging.patternfly.org/components/wizard/react-demos/in-modal/
* https://staging.patternfly.org/components/table/react-demos/column-management-with-draggable/ (click "manage columns" button)

It's from this block in the styles, but I'm not sure where it's coming from

```scss
/* This is for the Code Modals, so they act like they're part of the
/* chatbot. The PF modal doesn't allow us to change the position in
/* a more targeted way, because you can only add classes onto the
/* dialog itself.  */
.pf-v6-c-backdrop {
  position: static;
}
```

cc @nicolethoen
