### ISSUE TITLE
There is an unexpected space between table toolbar and datatable

### ISSUE THREAD

**Issue by matthewcarleton** [patternfly/patternfly-org#514]
This is being moved from the patternfly core repo seen here [#932](https://github.com/patternfly/patternfly/issues/932)

**Comment by dabeng** [comment]
Hi @matthewcarleton @mcarrano .The issue is cased by the following css snippets of pattern-site.css.
```css
.example-pf .blank-slate-pf,.example-pf .dataTables_wrapper,.example-pf .progress,.example-pf .toolbar-pf {
    margin-bottom: 10px
}
```

**Comment by matthewcarleton** [comment]
@dabeng thanks, ya I saw this. Without investigating too deeply I didn't see the reason for this being added. I think it's likely added without the consideration of how .example-pf .toolbar-pf can affect more than just the desired toolbar.

**Comment by dabeng** [comment]
@matthewcarleton , you are right. The table view is composed of toolbar-pf and dataTables_wrapper. The above setting applies only to single toolbar-pf or dataTables_wrapper.

**Comment by matthewcarleton** [comment]
@dabeng can you investigate this further and track down where that margin is needed? I'm assuming if we just remove it something will not look good.

**Comment by dabeng** [comment]
Hi @matthewcarleton . I'm glad to fix it. The following is preliminary solution:
source/_includes/code/content-views/table-view/code.md
```md
<div class="example-pf table-view-pf"> // line 4
 {% include widgets/table-view/table-view.html %}
</div>
```

source/_less/patternfly-site.less
```css
.example-pf {
 ...
  &.table-view-pf {  // line 194
    .dataTables_wrapper,
    .toolbar-pf { margin-bottom: 0; }
  }
 ...
}
```
Here‘s the **[demo](https://rawgit.com/dabeng/patternfly-org/dt-space-dist/_site/pattern-library/content-views/table-view/)** page.
@mcarrano @jeff-phillips-18 @jgiardino Do you have any thoughts about this bug-fix ?

**Comment by matthewcarleton** [comment]
hey @dabeng thanks for looking into this. A couple questions: why do we need a preliminary solution here? I also wonder if it's better to rewrite the original css to target what needs styling rather than overwrite it with what you have here.

**Comment by dabeng** [comment]
Hi @matthewcarleton , thanks for continuous attention 😊. For the sake of coming to an agreement on final solution, I put forward my preliminary solution as reference. As for second question, I apply incremental changes¹ in order to not interfere with current margin-bottom setting². in other words, I provide code 1 setting especially for the combination of toolbar-pf and dataTables_wrapper.
code 1
```css
.example-pf.table-view-pf .dataTables_wrapper, .example-pf.table-view-pf .toolbar-pf {
    margin-bottom: 0;
}
```
code 2
```css
.example-pf .blank-slate-pf, .example-pf .dataTables_wrapper, .example-pf .progress, .example-pf .toolbar-pf {
    margin-bottom: 10px;
}
```
